### ISSUE TITLE
SDXLRefinerClipModel ERROR

### ISSUE THREAD

**Issue by shuurik** [BoosterCore/ChaosFlow#1]
Hi, 请问在复现HDRI工作流的时候, Eff.Loader SDXL 一直报错, 模型我也改过几个, Refiner的问题吗? 
Error occurred when executing Eff. Loader SDXL:  'SDXLRefinerClipModel' object has no attribute 'clip_l'

**Comment by BoosterCore** [comment]
我打开试了一下，并没有这个报错现象呀

**Comment by BoosterCore** [comment]
> Hi, 请问在复现HDRI工作流的时候, Eff.Loader SDXL 一直报错, 模型我也改过几个, Refiner的问题吗? Error occurred when executing Eff. Loader SDXL: 'SDXLRefinerClipModel' object has no attribute 'clip_l'

![image](https://github.com/BoosterCore/ChaosFlow/assets/73834045/730d6ffb-db86-4242-a548-8551ffc29903)
看看会不会是这个原因，建议把Efficiency重装一下

**Comment by shuurik** [comment]
搞定了感谢
