### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hzeasy** [BoosterCore/ChaosFlow#2]
Hello, I have an error ('NoneType' object is not subscriptable) ​​when reproducing this workflow (IPAdapter AnimateDiff Prompt Travle With Frame Interpolation v1.0). I ​​have tried many methods but cannot solve it. Please help me check it out.

![39b2b9a92a103ba573d240946698020](https://github.com/BoosterCore/ChaosFlow/assets/136664755/4855ac89-c155-44b6-990e-db257e407c8f)
Are there any requirements for the input image resolution?
![8db490bbe241631be5c1c95bef09453](https://github.com/BoosterCore/ChaosFlow/assets/136664755/365fcd7a-9357-4776-8693-5f2fc680926b)

**Comment by BoosterCore** [comment]
Have you updated comfyui and installed custom nodes?

**Comment by BoosterCore** [comment]
I never used the ipadapter model you used, not sure they are ok.

**Comment by hzeasy** [comment]
I'm glad that the previous problem has been solved, which is the result after updating comfyui. But a new problem comes again, haha! Please help to check again.
![7785e0e51e3f7e10674f879dc0707f2](https://github.com/BoosterCore/ChaosFlow/assets/136664755/30cfffd1-3047-454c-b654-0126a5d4a759)
@BoosterCore

**Comment by BoosterCore** [comment]
The original author of efficiency nodes has stopped updating, and is now being updated by a new author. You may need to use the manager to uninstall the original version and reinstall the new version.

**Comment by hzeasy** [comment]
> The original author of efficiency nodes has stopped updating, and is now being updated by a new author. You may need to use the manager to uninstall the original version and reinstall the new version.

You are correct, after updating everything it worked fine. thank you for sharing。
