### ISSUE TITLE
SVD工作流

### ISSUE THREAD

**Issue by solitaryTian** [BoosterCore/ChaosFlow#4]
你好。我在https://www.youtube.com/watch?v=uF06pD0l4R4&ab_channel=KevinHu上看到了您将LCM和SVD结合的工作流。评论区把我指引到这里。但我并没有看到SVD的相关工作流。请问可否上传一下呢？非常感谢~~~

**Comment by BoosterCore** [comment]
> 你好。我在[https://www.youtube.com/watch?v=uF06pD0l4R4&ab_channel=KevinHu上看到了您将LCM和SVD结合的工作流。评论区把我指引到这里。但我并没有看到SVD的相关工作流。请问可否上传一下呢？非常感谢](https://www.youtube.com/watch?v=uF06pD0l4R4&ab_channel=KevinHu%E4%B8%8A%E7%9C%8B%E5%88%B0%E4%BA%86%E6%82%A8%E5%B0%86LCM%E5%92%8CSVD%E7%BB%93%E5%90%88%E7%9A%84%E5%B7%A5%E4%BD%9C%E6%B5%81%E3%80%82%E8%AF%84%E8%AE%BA%E5%8C%BA%E6%8A%8A%E6%88%91%E6%8C%87%E5%BC%95%E5%88%B0%E8%BF%99%E9%87%8C%E3%80%82%E4%BD%86%E6%88%91%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%9C%8B%E5%88%B0SVD%E7%9A%84%E7%9B%B8%E5%85%B3%E5%B7%A5%E4%BD%9C%E6%B5%81%E3%80%82%E8%AF%B7%E9%97%AE%E5%8F%AF%E5%90%A6%E4%B8%8A%E4%BC%A0%E4%B8%80%E4%B8%8B%E5%91%A2%EF%BC%9F%E9%9D%9E%E5%B8%B8%E6%84%9F%E8%B0%A2)~~~

https://github.com/BoosterCore/ChaosFlow/tree/main/Workflows/Movie%20Storyboard%20Generator
Movie Storyboard Generator
