### ISSUE TITLE
老师你好，我下载最近的纹理生成节点v2导入时出错

### ISSUE THREAD

**Issue by 253701** [BoosterCore/ChaosFlow#6]
我在b站一直关注老师的动态，每个视频都有仔细学习，这次下载纹理v2节点导入时出错，我尝试了各种方法都没有得到解决，老师分享的其他工作流我导入都是正常运作的，
已安装所有必须节点，comfy更新的最新版，出现错误时把安装的所有第三方节点全部一出再次导入还是报错，
![CX98T$MZJI{$RSM W_I7@EO](https://github.com/BoosterCore/ChaosFlow/assets/127170526/f32e7b15-0bf8-4492-bd97-fc09f5c09435)
![M2GQQC30ZU(Y1EY)WY74Z S](https://github.com/BoosterCore/ChaosFlow/assets/127170526/c7b95867-8eb1-4a02-adfe-912167e0e430)
，并且有许都节点全部都叠在一起，手动分开后并不是相连的，我没有接触过这么复杂的节点，自己也不会手动链接，
我查的好像是和那重远程发送，全局输入之类的节点有关{并不确定，我这里全局输入节点没导入这个工作流之前就使用着有bug，并且没找到解决办法和排除引起的原因}，老师方便的时候可以传一份连线版本的吗，或着传一张流程图，我直接照着连

**Comment by BoosterCore** [comment]
manager中搜索 diffus3这套节点，安装一下试试

**Comment by 253701** [comment]
> manager中搜索 diffus3这套节点，安装一下试试

老师，这套节点我之前有安装，是在用纹理v1时安装的，
![%9_DBZZ8WJ3$D@28A SMH F](https://github.com/BoosterCore/ChaosFlow/assets/127170526/5f83c31f-2921-4f2b-aa61-55f12a1c543d)

**Comment by BoosterCore** [comment]
图片版也在同一目录里

**Comment by 253701** [comment]
> 图片版也在同一目录里
两个我都尝试了，能想到的办法最后只剩下完全重装comfy，暂时只能先搁置，等老师未来的v3版本或者找时间完全重装comfy来解决，我在github和b站评论区内并没有看到其他人的报错问题，应该是我这里环境出了问题，期待老师的未来更新与新作品，

**Comment by Bhoja1234** [comment]
同样的问题，年前还能正常加载，不知道更新了什么之后就不行了

**Comment by Bhoja1234** [comment]
我暂时能把图片导入进去了，但是并不清楚能否运行。
1.打开setget.js文件，"./web/extensions/diffus3/setget/setget.js"
第57行需要修改，由：
`const type = fromNode.outputs[link_info.origin_slot].type;`
改为：
`const type = fromNode.outputs[link_info.origin_slot]?.type;`
保存重启
2.重新加载图片会显示有一些节点未安装，安装好后再次重新加载图片，应该就不会弹窗报错了
3.最后记得把57行修改的代码还原

注：我这样做，只是成功把工作流导入进去了。

**Comment by BoosterCore** [comment]
比较奇怪，我这边已经把Comfy UI和所有Custom Nodes都升级到了最新版，测试这个工作流程是可以正常运行的。

**Comment by 253701** [comment]
我把内核版本降级重装已经可以用了

**Comment by BoosterCore** [comment]
> 我把内核版本降级重装已经可以用了

2024_03_06我更新了一版，匹配了最新版的WAS节点。

**Comment by wuya2408** [comment]
> 我把内核版本降级重装已经可以用了

你好 请问你内核降低到多少可以使用 我也遇见了相同问题
